### ISSUE TITLE
jupyter notebook加载缓慢，可以把阅读链接直接附在README里面

### ISSUE THREAD

**Issue by joexu01** [543877815/visualization-tutorials#1]
>在Github上虽然能够直接加载ipynb文件，但是速度很慢，并且容易加载失败。利用https://nbviewer.jupyter.org/ 可以快速加载ipynb文件

CSDN上的解决方案：[点我点我](https://blog.csdn.net/weiwei9363/article/details/79438908)

给君哥生成的阅读链接：[点我点我](https://nbviewer.jupyter.org/github/543877815/visualization-tutorials/blob/master/matplotlib/matplotlib-beginner.ipynb)

君哥牛逼！学习了^_^

**Comment by 543877815** [comment]
给我提pr
